name: Deploy to GitHub Pages
on:
  push:
    branches:
      - release
permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2 # Only works with v2
      - uses: subosito/flutter-action@v1

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_APOD_URL: ${{ vars.APOD_URL }}
          ENV_APOD_API_KEY: ${{ secrets.APOD_API_KEY }}

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Download Dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build
        run: flutter build web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'